title: "[회의록] 2025-XX-XX"
body:
  - type: textarea
    attributes:
      label: 데일리 미팅
      value: |
        ## 주요 논의 내용
        1. **안건 1**: 내용 작성
        2. **안건 2**: 내용 작성
        
        ## 결정사항
        - 결정 1: 내용 작성
        - 결정 2: 내용 작성
        
        ## Action Items
        - [ ] Task 1 (담당자: 이름)
        - [ ] Task 2 (담당자: 이름)
